# Numpy: Functions

Now that we're comfortable **creating** data with **Numpy**, let's learn how to **manipulate** the data that we've created. 

In [1]:
import numpy as np

## Matrix arithmetic and linear algebra

Let's do some basic arithmetic. First, make a matrix using `as.array()`. One way to use `as.array()` is to supply a list of lists, where each list is a **row** of our matrix. 

In [2]:
A = np.asarray([[1,2],[0,1]])
B = np.asarray([[1,0],[2,1]])
print(A)
print(B)

[[1 2]
 [0 1]]
[[1 0]
 [2 1]]


The `+` operator in regular Python does exactly what you think it will do. `np.add()` is Numpy's version of the same thing. 

In [3]:
print('sum:\n', A+B)

sum:
 [[2 2]
 [2 2]]


In [4]:
print('sum:\n', np.add(A,B))

sum:
 [[2 2]
 [2 2]]


 The `*` operator in regular Python yields **elementwise multiplication** (not matrix multiplication!). `np.multiply()` is Numpy's way to do elementwise multiplication.

In [5]:
print('elementwise multiplication:\n', A*B)

elementwise multiplication:
 [[1 0]
 [0 1]]


In [6]:
print('elementwise multiplication:\n', np.multiply(A,B))

elementwise multiplication:
 [[1 0]
 [0 1]]


Using regular python, we can use the character `@` to perform **matrix multiplication**. Using Numpy, we can use the `dot` method.

In [10]:
print('dot product:\n',A@B)

dot product:
 [[5 2]
 [2 1]]


In [7]:
print('dot product:\n',np.dot(A,B))

dot product:
 [[5 2]
 [2 1]]


How about the **inverse** and **transpose** of a matrix using Numpy?

In [12]:
# inverse of A
print(np.linalg.inv(A))

[[ 1. -2.]
 [ 0.  1.]]


In [13]:
# traspose of A
print(A.T)

[[1 0]
 [2 1]]


`np.sum()` computes the sum of elements in a matrix. We can also specify which axis we would like to sum over, thereby obtaining **column sums** or **row sums**. 

In [9]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1))  # Compute sum of each row

10
[4 6]
[3 7]


## Reshaping and axis swapping

You can **reshape** a matrix given that the number of elements is unchanged.

In [14]:
a_long_vector = np.asarray(range(30))
as_matrix = a_long_vector.reshape(5,6)
print(as_matrix)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


Above, the matrix was re-shaped in a **row-wise** fashion. If we wish to reshape in a **column-wise** fashion, we can specify the argument `order = F`. Notice the difference between the previous matrix and this one:

In [16]:
another_matrix = a_long_vector.reshape(5,6,order='F')
print(another_matrix)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


## Concatenating 

**Concatening** two arrays involves combining them along all axes for which they have the same size. This is how we can create a 'tall' table out of two shorter ones... or a 'wide' table out of two skinny ones. 

In [17]:
# create an empty matrix
A = np.empty([5,5])
B = np.empty([3,5])

# concatenate along the first axis
C = np.concatenate([A,B],axis=0)
print(C.shape)

(8, 5)


In [20]:
# create an empty matrix
D = np.empty([6,2])
E = np.empty([6,1])

# concatenate along the second axis
F = np.concatenate([E,D],axis=1)
print(F.shape)

(6, 3)
