# Numpy: Structures

The first step to using any third-party package (like Numpy or Matplotlib) is to **import** the package. This can be accomplished using the function `import()`. 

To make coding easier, we typically like to give each package a **nickname**. In this example, we import the package **Numpy** with the nickname **"np"**. It will become clear why nicknames are helpful. 

In [2]:
import numpy as np

Now, we are ready to use the package that we've nicknamed "np". 

**Numpy** functions can be called by typing "**np**" followed by a period and then the name of the function.

Let's start by making a simple vector. 

In [3]:
# make a vector with 10 elements
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# make a vector from 2 to 10 where type = float
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
# make a vector from 2 to 3 by increment = 0.1
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [6]:
# make a vector from 1 to 4 with 6 elements total
np.linspace(1, 4, 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

We can **index** into any value of the vector using square brackets [ ]. 

In [23]:
x = np.arange(10)
x[9]

9

## `ndarray`

Often, we want higher-dimension data structures such as matrices. **Numpy** has a matrix data structure called the **`ndarray`**. An `ndarray` can can be any number of dimensions! (`ndarray` stands for n-dimensional array). 

In [3]:
#1-dimensional (vector)
test = np.array([1,2,3,4,5])
print(test)

[1 2 3 4 5]


In [4]:
#2-dimensional (matrix)
test = np.array([[1,3],[2,4]])
print(test)

[[1 3]
 [2 4]]


There's a function called `np.zeros()` that makes a matrix entirely of **zeros**.

In [27]:
# make a 4x4 array of zeros
all_zero = np.zeros([4,4]) 
print(all_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Recall that the `type()` function can be used to examine the **type** of an object or variable. 

In [28]:
print(type(all_zero))

<class 'numpy.ndarray'>


Use `np.ones()` to fill an array with **ones**.  

In [29]:
all_one = np.ones([6,2])
print(all_one)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


An `ndarray()` can be any shape or size! Let's make a 4-dimensional array of ones.

In [30]:
big_ones = np.ones([4,5,2,2])

These arrays can be thought of as generalizations of **vectors** or **matrices**.

Note that a vector or scalar requires a single integer, while objects with dimension > 1 require a **sequence** of integers. 

In [17]:
matrix = np.ones([2,2])
vector = np.ones([2])
scalar = np.ones(1)

To find the number of **elements** in the array, we use the `size()` attribute. To find the array **dimensions**, we use `shape()`.

In [31]:
another_array = np.ones([10,13,2])
print(another_array.size)
print(another_array.shape)

260
(10, 13, 2)


## Multidimensional indexing and slicing

Since the `ndarray` can have multiple **axes** or **dimensions**, we need to know how to access **subsets** or **slices** of these values. Slicing is accomplished using square brackets [ ].

In [ ]:
# Creates 10 x 10 x 10 x 10 array of randomly sampled values from a standard normal distribution.
original = np.random.randn(10,10,10,10)

In [7]:
# subset the array 
# Dimension 1: first 2 elements
# Dimension 2: first 2 elements
# Dimension 3: first 3 elements
# Dimension 4: first 4 elements
subset = original[0:2,0:2,0:3,0:4]
print(subset.shape)
print(subset.size)

NameError: name 'original' is not defined

## Loading from files

You can also **import** and **export** data using Numpy. You should check out the [documentation]( https://numpy.org/doc/1.17/user/basics.io.html) for the full set of functions for importing and exporting files. 

Here is a quick example:

In [8]:
from io import StringIO

In [10]:
# make some comma-saparated data
data = "1, 2, 3\n4, 5, 6"
print(data)

# import the data, and turn it into an array
np.genfromtxt(StringIO(data), delimiter=",")

1, 2, 3
4, 5, 6


array([[1., 2., 3.],
       [4., 5., 6.]])